services:
  db:
    image: mysql:8.0
    container_name: qrapp-mysql
    restart: unless-stopped
    env_file: .env.dev
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:ro
      - qrapp-mysql-data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: qrapp-adminer
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"

volumes:
  qrapp-mysql-data:
